global using Dapr;
global using Dapr.Client;
global using Dapr.Extensions.Configuration;
global using HealthChecks.UI.Client;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using AWC.Shared.Kernel.Utilities;
global using Awc.Dapr.BuildingBlocks.EventBus;
global using Awc.Dapr.BuildingBlocks.EventBus.Abstractions;
global using Awc.Dapr.BuildingBlocks.EventBus.Events;
global using Awc.Dapr.Services.Company.API;
global using Awc.Dapr.Services.Company.API.Infrastructure;
global using Awc.Dapr.Services.Company.API.Infrastructure.EntityConfigurations;
// global using Awc.Dapr.Services.Company.API.IntegrationEvents.EventHandling;
// global using Awc.Dapr.Services.Company.API.IntegrationEvents.Events;
global using Awc.Dapr.Services.Company.API.Model.Company;
global using Awc.Dapr.Services.Company.API.Model.Employees;
global using Awc.Dapr.Services.Company.API.Model.Person;
// global using Awc.Dapr.Services.Company.API.ViewModel;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Diagnostics.HealthChecks;
global using Microsoft.Extensions.FileProviders;
global using Microsoft.Extensions.Hosting;
global using Microsoft.OpenApi.Models;
global using Mapster;
global using MapsterMapper;
global using Polly;
global using System.Net;
global using Serilog;
