version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The AWC_DAPR_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     AWC_DAPR_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file

services:

  zipkin:
    ports:
      - "5411:9411"

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  company-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__CompanyApi=Server=tcp:ubuntu-svr,5434;Database=CompanyAPI;uid=sa;Password=Info99Gum;TrustServerCertificate=True
      - RetryMigrations=true
      - SeqServerUrl=http://seq

    ports:
      - "5052:80"
      - "50002:50001"

  company-api-dapr:
    command: ["./daprd",
      "-app-id", "company-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/awc-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

